image: node:18

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build'
          caches:
            - node
          script:
            - npm install
            - npm run build --prod
      - step:
          name: 'Lint'
          caches:
            - node
          script:
            - npm install
            - npm run lint
      - step:
          name: 'Tests'
          caches:
            - node
          script:
            - npm install
            - npm run test

  branches:
    master:
      - step:
          name: 'Deployment to Staging'
          caches:
            - node
          deployment: staging
          script:
            - npm install -g firebase-tools
            - npm install
            - npm run build --prod
            - firebase deploy --token $FIREBASE_TOKEN --project <YOUR_FIREBASE_PROJECT_ID>
